name: Rust

on:
  push:
  pull_request:

jobs:
  check-esp32c3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.88.0"
          targets: riscv32imc-unknown-none-elf
          components: clippy
      - run: cargo check -p esp-storage-manager --features esp32c3 --target riscv32imc-unknown-none-elf
      - run: cargo clippy -p esp-storage-manager --features esp32c3 --target riscv32imc-unknown-none-elf -- -D warnings
      - run: cargo check -p esp-config-space-backend --features esp32c3 --target riscv32imc-unknown-none-elf
      - run: cargo clippy -p esp-config-space-backend --features esp32c3 --target riscv32imc-unknown-none-elf -- -D warnings
